module.exports = {
    SUCCESS_CODE: 200,
    CREATED: 201,
    REQ_DATING_ERROR_CODE: 204,
    ERROR_CODE: 400,
    INVALID_CODE: 401,
    FORBIDDEN_CODE: 403,
    INACTIVATE: 406,
    NOT_FOUND: 404,
    CONFLICT: 409,
    REQUEST_NOT_FOUND: 'Request not found',
    EMAIL_ALREADY_REGISTERED: 'Email already registered.',
    INVAILID_DATA: 'Registration form data is not correct.',
    USER_SAVE_SUCCESS: 'Registration completed successfully',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    USER_LOGIN_SUCCESS: 'User Login successfully',
    USER_VERIFICATION_SUCCESS: 'User verified',
    USER_EMAIL_PASSWORD: "You have entered an invalid email or password",
    EMAIL_VERIFIED: 'Email successfully verified.',
    INVALID_TOKEN: "Invalid Token",
    USER_EMAIL_NOT_REGISTERED: "This email is not registered.",
    SENT_FORGOT_EMAIL: "Email sent successfully.",
    USER_RESET_PASSWORD:'Reset password token expires! Regenerate token to set password',
    USER_OLD_PASSWORD:'User old password did not matched',
    PASSWORD_RESET: "Password reset successfully",
    BLOG_SAVE_SUCCESS: 'Blog created successfully',
    BLOG_UPDATED_SUCCESS: 'Blog updated successfully',
    BLOG_DELETED_SUCCESS: 'Blog deleted successfully',
    BLOG_CATEGORY_SAVE_SUCCESS: 'Blog category created successfully',
    BLOG_CATEGORY_UPDATED_SUCCESS: 'Blog category updated successfully',
    BLOG_CATEGORY_DELETED_SUCCESS: 'Blog category deleted successfully',
    BLOG_RETRIEVE_SUCCESS: 'Blog retrieve successfully',
    BLOG_CATEGORY_SAVE_SUCCESS: 'Blog category created successfully',
    BLOG_COMMENT_SAVE_SUCCESS: 'Blog comment created successfully',
    EVENT_RETRIEVE_SUCCESS: 'Events retrieve successfully',
    EVENT_SAVE_SUCCESS: 'Event created successfully',
    EVENT_UPDATED_SUCCESS: 'Event updated successfully',
    Event_DELETED_SUCCESS: 'Evet deleted successfully',
    EVENT_CATEGORY_SAVE_SUCCESS: 'Blog category created successfully',
    EVENT_CATEGORY_UPDATED_SUCCESS: 'Event category updated successfully',
    EVENT_CATEGORY_DELETED_SUCCESS: 'Event category deleted successfully',
    BOOK_CATEGORY_SAVE_SUCCESS: 'Book category created successfully',
    BOOK_CATEGORY_UPDATED_SUCCESS: 'Book category updated successfully',
    BOOK_CATEGORY_DELETED_SUCCESS: 'Book category deleted successfully',
}